# Starting from apline base image
FROM alpine:latest
RUN apk update

# Install dependencies for desktop flutter run
RUN apk add --no-cache git
RUN apk add --upgrade bash clang14 cmake ninja pkgconf gtk+3.0-dev xz-dev curl

# Switching shell to bash
SHELL ["/bin/bash", "-c"]

# Installing flutter and setting environment variables
RUN git clone https://github.com/flutter/flutter.git -b stable /usr/local/flutter
ENV PATH="$PATH:/usr/local/flutter/bin"
RUN rm -rf /usr/loca/flutter/bin/cache
RUN flutter pub cache repair
RUN flutter doctor

# Creating new project
WORKDIR $HOME/stormimpact_dashboard
ADD . .
CMD ["flutter", "run"]
