# Pulling ubuntu base image
FROM ubuntu:22.10
RUN apt-get update
SHELL ["/bin/bash", "-c"]

# Install dependencies for desktop flutter run
RUN apt-get install -y --no-install-recommends \
	clang \
	cmake \
	libgtk-3-dev \
	ninja-build \
	pkg-config \
	x11-xserver-utils \
	xauth \
	xvfb \
	curl \
	unzip \ 
	git && \
	apt-get upgrade -y --no-install-recommends && \
	apt-get clean

# Set up new user
# RUN useradd -ms /bin/bash developer
# USER developer
# WORKDIR /home/developer

# Installing flutter and dependencies
RUN git clone https://github.com/flutter/flutter.git -b stable /usr/local/flutter
ENV PATH="$PATH:/home/developer/flutter/bin"
RUN flutter doctor

# ADD . /home/developer/stormimpact_dashboard
# WORKDIR /home/developer/stormimpact_dashboard
# CMD ["flutter", "run"]
RUN flutter new 
# CMD ["bash"]
